version: '3.1'

services:
  keycloak-dev:
    image: quay.io/keycloak/keycloak:17.0.1
    ports:
    - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: secret
    command: start-dev
  openldap:
    image: osixia/openldap:latest
    environment:
    - LDAP_ORGANISATION="My Company"
    - LDAP_DOMAIN=example.org
    - LDAP_ADMIN_PASSWORD=admin
    - LDAP_SEED_INTERNAL_LDIF_PATH=/home/ldap-openldap-docker-init.ldif
    volumes:
    - ./ldap-openldap-docker-init.ldif:/home/ldap-openldap-docker-init.ldif
  ldap-admin:
    image: osixia/phpldapadmin:latest
    ports:
    - "8001:80"
    environment:
    - PHPLDAPADMIN_LDAP_HOSTS=ldap://openldap
    - PHPLDAPADMIN_HTTPS=false
